name: chuck_norris_mvvm
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  go_router: ^11.1.4
  get_it: ^7.6.4
  lottie: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.8

flutter:
  uses-material-design: true

  assets:
    - assets/lottie/
    - assets/icon/

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon/dash_app_icon.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#3b3b3b"
  image: "assets/icon/dash_app_icon.png"
